version: "3.9"

services:
  web:
    build: .
    container_name: django_web
    volumes:
      - .:/code
      - static_volume:/code/static
    expose:
      - "8000"
    depends_on:
      - nginx

  nginx:
    image: nginx:alpine
    container_name: django_nginx
    ports:
      - "80:80"
    volumes:
      - static_volume:/code/static
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web

volumes:
  static_volume:
