services:
  web:
    build: .
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - .:/code
      - ./nginx/CA/client-ca.crt:/etc/nginx/tls/client-ca-bundle.pem:ro
    environment:
      - DJANGO_SETTINGS_MODULE=django_project.settings
