services:
  web:
    build: .
    ports:
      - "8001:80"
      - "8010:443"
    volumes:
      - .:/code
      - static_volume:/var/www/static
      - media_volume:/var/www/media
    environment:
      - DJANGO_SETTINGS_MODULE=django_project.settings

volumes:
  static_volume:
  media_volume:
