services:
  web:
    build: .
    ports:
      - "8000:80"
    volumes:
      - .:/code
      - static_volume:/var/www/static
      - media_volume:/var/www/media
    environment:
      - DJANGO_SETTINGS_MODULE=django_project.settings
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
  static_volume:
  media_volume: