

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - static_volume:/code/static
      - media_volume:/code/media
    networks:
      - app_network
    depends_on:
      - web
    entrypoint: [ "/entrypoint.sh" ]

  web:
    build: .
    command: ["gunicorn", "django_project.wsgi:application", "--bind", "0.0.0.0:8000"]
    volumes:
      - static_volume:/code/static
      - media_volume:/code/media
    networks:
      - app_network
    environment:
      - DEBUG=1
    expose:
      - "8000"

volumes:
  static_volume:
  media_volume:

networks:
  app_network:
    driver: bridge
