# Generated by Django 5.2.1 on 2025-05-19 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='HashFunction',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=30, unique=True)),
                ('digest_size', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SigningAlgorithm',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Signer',
            fields=[
                ('unique_id', models.AutoField(primary_key=True, serialize=False)),
                ('unique_name', models.CharField(max_length=30, unique=True)),
                ('key_length', models.IntegerField()),
                ('private_key', models.TextField()),
                ('certificate', models.TextField()),
                ('expires_by', models.DateTimeField()),
                ('created_by', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                (
                    'hash_function',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to='signers.hashfunction',
                    ),
                ),
                (
                    'signing_algorithm',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to='signers.signingalgorithm',
                    ),
                ),
            ],
        ),
    ]
