# Generated by Django 5.1.8 on 2025-06-26 09:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('signers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signer',
            name='key_length',
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, '2048 Bits'),
                    (2, '3072 Bits'),
                    (3, '4096 Bits'),
                    (4, '8192 Bits'),
                ],
                null=True,
            ),
        ),
    ]
