# Generated by Django 5.2.1 on 2025-05-21 19:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('signers', '0002_alter_signer_signing_algorithm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signer',
            name='certificate',
            field=models.CharField(max_length=4096),
        ),
        migrations.AlterField(
            model_name='signer',
            name='private_key',
            field=models.CharField(max_length=4096),
        ),
        migrations.AlterField(
            model_name='signer',
            name='signing_algorithm',
            field=models.CharField(
                choices=[
                    ('RSA', 'RSA'),
                    ('ECDSA', 'ECDSA'),
                    ('Ed25519', 'Ed25519'),
                    ('Ed448', 'Ed448'),
                ],
                max_length=50,
            ),
        ),
    ]
