# Generated by Django 5.2.1 on 2025-05-22 07:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('signers', '0003_alter_signer_certificate_alter_signer_private_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signer',
            name='hash_function',
            field=models.CharField(
                choices=[
                    ('1.2.840.113549.2.5', 'MD5'),
                    ('1.3.14.3.2.26', 'SHA1'),
                    ('2.16.840.1.101.3.4.2.4', 'SHA224'),
                    ('2.16.840.1.101.3.4.2.1', 'SHA256'),
                    ('2.16.840.1.101.3.4.2.2', 'SHA384'),
                    ('2.16.840.1.101.3.4.2.3', 'SHA512'),
                    ('2.16.840.1.101.3.4.2.7', 'SHA3-224'),
                    ('2.16.840.1.101.3.4.2.8', 'SHA3-256'),
                    ('2.16.840.1.101.3.4.2.9', 'SHA3-384'),
                    ('2.16.840.1.101.3.4.2.10', 'SHA3-512'),
                    ('2.16.840.1.101.3.4.2.11', 'Shake-128'),
                    ('2.16.840.1.101.3.4.2.12', 'Shake-256'),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name='signer',
            name='signing_algorithm',
            field=models.CharField(
                choices=[
                    ('1.2.840.113549.1.1.4', 'RSA with MD5'),
                    ('1.2.840.113549.1.1.5', 'RSA with SHA1'),
                    ('1.3.14.3.2.29', 'RSA with SHA1'),
                    ('1.2.840.113549.1.1.11', 'RSA with SHA256'),
                    ('1.2.840.113549.1.1.12', 'RSA with SHA384'),
                    ('1.2.840.113549.1.1.13', 'RSA with SHA512'),
                    ('2.16.840.1.101.3.4.3.13', 'RSA with SHA3-224'),
                    ('2.16.840.1.101.3.4.3.14', 'RSA with SHA3-256'),
                    ('2.16.840.1.101.3.4.3.15', 'RSA with SHA3-384'),
                    ('2.16.840.1.101.3.4.3.16', 'RSA with SHA3-512'),
                    ('1.2.840.10045.4.1', 'ECDSA with SHA1'),
                    ('1.2.840.10045.4.3.1', 'ECDSA with SHA224'),
                    ('1.2.840.10045.4.3.2', 'ECDSA with SHA256'),
                    ('1.2.840.10045.4.3.3', 'ECDSA with SHA384'),
                    ('1.2.840.10045.4.3.4', 'ECDSA with SHA512'),
                    ('2.16.840.1.101.3.4.3.9', 'ECDSA with SHA3-224'),
                    ('2.16.840.1.101.3.4.3.10', 'ECDSA with SHA3-256'),
                    ('2.16.840.1.101.3.4.3.11', 'ECDSA with SHA3-384'),
                    ('2.16.840.1.101.3.4.3.12', 'ECDSA with SHA3-512'),
                    ('1.2.840.113533.7.66.13', 'Password Based MAC'),
                ],
                max_length=50,
            ),
        ),
        migrations.DeleteModel(
            name='HashFunction',
        ),
    ]
