# Generated by Django 5.1.8 on 2025-07-07 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('signers', '0003_alter_signer_key_length'),
        ('users', '0002_usertoken_created_at_usertoken_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signedmessage',
            name='token',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='users.usertoken',
            ),
        ),
    ]
