# Generated by Django 5.1.8 on 2025-08-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('signers', '0004_signedmessage_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signedmessage',
            name='token',
        ),
        migrations.AddField(
            model_name='signedmessage',
            name='cert_subject',
            field=models.TextField(blank=True, null=True),
        ),
    ]
