# Generated by Django 5.2.1 on 2025-05-22 07:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('signers', '0004_alter_signer_hash_function_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signer',
            name='hash_function',
            field=models.CharField(max_length=50),
        ),
    ]
