# Generated by Django 5.2.1 on 2025-05-25 23:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('signers', '0005_alter_signer_hash_function'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signer',
            name='signing_algorithm',
            field=models.CharField(
                choices=[
                    ('1.2.840.113549.1.1.4', 'RSA with MD5'),
                    ('1.2.840.113549.1.1.5', 'RSA with SHA1'),
                    ('1.3.14.3.2.29', 'RSA with SHA1'),
                    ('1.2.840.113549.1.1.14', 'RSA with SHA224'),
                    ('1.2.840.113549.1.1.11', 'RSA with SHA256'),
                    ('1.2.840.113549.1.1.12', 'RSA with SHA384'),
                    ('1.2.840.113549.1.1.13', 'RSA with SHA512'),
                    ('2.16.840.1.101.3.4.3.13', 'RSA with SHA3-224'),
                    ('2.16.840.1.101.3.4.3.14', 'RSA with SHA3-256'),
                    ('2.16.840.1.101.3.4.3.15', 'RSA with SHA3-384'),
                    ('2.16.840.1.101.3.4.3.16', 'RSA with SHA3-512'),
                    ('1.2.840.10045.4.1', 'ECDSA with SHA1'),
                    ('1.2.840.10045.4.3.1', 'ECDSA with SHA224'),
                    ('1.2.840.10045.4.3.2', 'ECDSA with SHA256'),
                    ('1.2.840.10045.4.3.3', 'ECDSA with SHA384'),
                    ('1.2.840.10045.4.3.4', 'ECDSA with SHA512'),
                    ('2.16.840.1.101.3.4.3.9', 'ECDSA with SHA3-224'),
                    ('2.16.840.1.101.3.4.3.10', 'ECDSA with SHA3-256'),
                    ('2.16.840.1.101.3.4.3.11', 'ECDSA with SHA3-384'),
                    ('2.16.840.1.101.3.4.3.12', 'ECDSA with SHA3-512'),
                    ('1.2.840.113533.7.66.13', 'Password Based MAC'),
                ],
                max_length=50,
            ),
        ),
    ]
