# Generated by Django 5.1.8 on 2025-09-02 10:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('signers', '0005_remove_signedmessage_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signedmessage',
            name='cert_subject',
        ),
    ]
