# Generated by Django 5.1.8 on 2025-09-02 11:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('signers', '0006_remove_signedmessage_cert_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='signedmessage',
            name='cert_subject',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
