# Generated by Django 5.2.1 on 2025-05-26 06:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('signers', '0006_alter_signer_signing_algorithm'),
    ]

    operations = [
        migrations.AddField(
            model_name='signer',
            name='curve',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='signer',
            name='key_length',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
