# Generated by Django 5.2.1 on 2025-05-26 06:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('signers', '0007_signer_curve_alter_signer_key_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signer',
            name='curve',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
