# Generated by Django 5.2.1 on 2025-05-26 06:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('signers', '0008_alter_signer_curve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signer',
            name='curve',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
