# Generated by Django 5.2.1 on 2025-06-02 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('signers', '0009_alter_signer_curve'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignedMessage',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('hash_value', models.CharField(max_length=256)),
                ('signature', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'signer',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='signed_messages',
                        to='signers.signer',
                    ),
                ),
            ],
        ),
    ]
