# Generated by Django 5.2.1 on 2025-06-25 09:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('signers', '0010_signedmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signer',
            name='curve',
            field=models.CharField(
                blank=True,
                choices=[
                    ('None', 'None'),
                    ('1.2.840.10045.3.1.1', 'SECP192R1'),
                    ('1.3.132.0.33', 'SECP224R1'),
                    ('1.3.132.0.10', 'SECP256K1'),
                    ('1.2.840.10045.3.1.7', 'SECP256R1'),
                    ('1.3.132.0.34', 'SECP384R1'),
                    ('1.3.132.0.35', 'SECP521R1'),
                    ('1.3.36.3.3.2.8.1.1.7', 'BRAINPOOLP256R1'),
                    ('1.3.36.3.3.2.8.1.1.11', 'BRAINPOOLP384R1'),
                    ('1.3.36.3.3.2.8.1.1.13', 'BRAINPOOLP512R1'),
                    ('1.3.132.0.1', 'SECT163K1'),
                    ('1.3.132.0.15', 'SECT163R2'),
                    ('1.3.132.0.26', 'SECT233K1'),
                    ('1.3.132.0.27', 'SECT233R1'),
                    ('1.3.132.0.16', 'SECT283K1'),
                    ('1.3.132.0.17', 'SECT283R1'),
                    ('1.3.132.0.36', 'SECT409K1'),
                    ('1.3.132.0.37', 'SECT409R1'),
                    ('1.3.132.0.38', 'SECT571K1'),
                    ('1.3.132.0.39', 'SECT571R1'),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='signer',
            name='key_length',
            field=models.IntegerField(
                blank=True,
                choices=[
                    (2048, '2048 bits'),
                    (3072, '3072 bits'),
                    (4096, '4096 bits'),
                    (8192, '8192 bits'),
                ],
                null=True,
            ),
        ),
    ]
